app/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "app"


urlpatterns = [
    path("", views.home_page, name="base"),
    path("create-product/", views.create_product, name="create_product"),
    path("edit/product/<slug>", views.edit_product, name="edit_product"),
    path("delete/product/<slug>", views.delete_product, name="delete_product"),
    path("add-wishlist/<slug>", views.add_wishlist, name="add_wishlist"),
    path("remove-wishlist/<slug>", views.remove_wishlist, name="remove_wishlist"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wallet/", views.store_wallet, name="store_wallet"),
    path(
        "products/",
        views.a_store_all_products,
        name="store_products",
    ),
    path(
        "product/<slug:slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "store/<slugified_store_name>/category/<slug:slug>/products/",
        views.store_category_products,
        name="store_category_products",
    ),
    path(
        "store/<slugified_store_name>/collections",
        views.all_store_products,
        name="all_store_products",
    ),
    path("store/", views.store_admin, name="store_admin"),
    path("store/<slugified_store_name>/", views.store, name="store"),
    path("categories/", views.all_category, name="all_category"),
    path("create-category/", views.add_category, name="create_category"),
    path("edit-category/<slug:slug>/", views.edit_category, name="edit_category"),
    path("delete-category/<slug:slug>/", views.delete_category, name="delete_category"),
    path("discount-products/", views.discount_products, name="discount_products"),
    path("coupon/", views.all_coupons, name="all_coupons"),
    path("create-coupon/", views.create_coupon, name="create_coupon"),
    path("delete-coupon/<str:pk>/", views.delete_coupon, name="delete_coupon"),
    path("customers/", views.all_customers, name="all_customers"),
    path("orders/", views.store_orders, name="store_orders"),
    path("unpaid-orders/", views.unpaid_store_orders, name="unpaid_store_orders"),
    path("order/<uuid:pk>/", views.store_order_detail, name="store_order_detail"),
    path("<slugified_store_name>/review/", views.store_review, name="store_review"),
    path(
        "<slugified_store_name>/create/review/product/<slug:slug>/",
        views.product_store_review,
        name="product_store_review",
    ),
    path("reviews/", views.store_review_list, name="store_review_list"),
    path("review/<str:pk>/", views.store_review_detail, name="store_review_detail"),
    path(
        "yearly/subscriptions/",
        views.yearly_subscription_plans,
        name="yearly_subscription_plans",
    ),
    path(
        "monthly/subscriptions/",
        views.monthly_subscription_plans,
        name="monthly_subscription_plans",
    ),
    path(
        "transanction-history/", views.transanction_history, name="transanction_history"
    ),
    path("store-staff/", views.store_staff_page, name="store_staff_page"),
    path("shipping/", views.shipping_method_list, name="shipping_method_list"),
    path(
        "notification/mark-as-read/<str:id>/",
        views.mark_notification_read,
        name="mark_notification_read",
    ),
    path(
        "customer/detail/<str:pk>/",
        views.store_customers_details,
        name="store_customers_details",
    ),
    path(
        "store/<slugified_store_name>/product/<slug:slug>/reviews/",
        views.product_review_list,
        name="product_review_list",
    ),
    path("company/reviews/", views.company_review, name="company_review"),
    path("company/team/", views.company_team, name="company_team"),
    path("get-state/<iso2>/", views.get_state, name="get_state"),
    path("get-city/<iso2>/", views.get_state, name="get_city"),
    path("notifications/", views.notification_page, name="notification_page"),
    path("newsletter/", views.newsletter_page, name="newsletter_page"),
    path("generate/newsletter/", views.generate_store_newsletter, name="generate_store_newsletter"),
    path("draft/newsletter/", views.draft_newsletter, name="draft_newsletter"),
    path("publish/newsletter/", views.publish_newsletter, name="publish_newsletter"),
    path("publish/draft/newsletter/<str:pk>", views.publish_draft_newsletter, name="publish_draft_newsletter"),
    path("delete/newsletter/<str:pk>/", views.delete_draft_newsletter, name="delete_draft_newsletter"),
    path("edit/draft/newsletter/<str:pk>/", views.edit_draft_newsletter, name="edit_draft_newsletter"),
    path("unsubscribe-newsletter/<slugified_store_name>/", views.unsubscribe_newsletter, name="unsubscribe_newsletter"),
    path("resubscribe-newsletter/<slugified_store_name>/", views.resubscribe_newsletter, name="resubscribe_newsletter"),
    path(
        "create/shipping-method/", views.add_shipping_method, name="add_shipping_method"
    ),
    path(
        "edit/shipping-method/<str:pk>",
        views.edit_shipping_method,
        name="edit_shipping_method",
    ),
    path(
        "delete/shipping-method/<str:pk>",
        views.delete_shipping_method,
        name="delete_shipping_method",
    ),
    path("shipping-company/", views.shipping_company_list, name="shipping_company_list"),
    path("add/shipping-company/", views.add_shipping_company, name="add_shipping_company"),
    path("edit/shipping-company/<str:pk>", views.edit_shipping_company, name="edit_shipping_company"),
    path("delete/shipping-company/<str:pk>", views.delete_shipping_company, name="delete_shipping_company"),
    path("faqs/", TemplateView.as_view(template_name='faqs.html'), name="faqs" ),
    path("terms/", TemplateView.as_view(template_name='terms.html'), name="terms" ),
    path("privacy-policy/", TemplateView.as_view(template_name='privacy-policy.html'), name="privacy_policy" ),
    
]

core/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls")),
    path("customer/", include("customer.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "app.views.custom_error_404"
handler500 = "app.views.custom_error_500"

customer/urls.py
from django.urls import path

from . import views

app_name = "customer"

urlpatterns = [
    path(
        "register/<slugified_store_name>/",
        views.customer_register,
        name="customer_register",
    ),
    path(
        "login/<slug:slugified_store_name>/",
        views.customer_login,
        name="customer_login",
    ),
    path(
        "logout/<slugified_store_name>/", views.customer_logout, name="customer_logout"
    ),
    path(
        "register/existing-user/<slugified_store_name>/",
        views.existing_user_customer_register,
        name="existing_user_customer_register",
    ),
    path(
        "<slugified_store_name>/logout", views.customer_logout, name="customer_logout"
    ),
    path(
        "<slugified_store_name>/product/<slug:slug>/",
        views.customer_product_detail,
        name="customer_product_detail",
    ),
    path(
        "<slugified_store_name>/profile/",
        views.customer_profile,
        name="customer_profile",
    ),
    path(
        "<slugified_store_name>/wishlist/",
        views.customer_wishlist,
        name="customer_wishlist",
    ),
    path(
        "add-wishlist/<slug>", views.customer_add_wishlist, name="customer_add_wishlist"
    ),
    path(
        "remove-wishlist/<slug>",
        views.customer_remove_wishlist,
        name="customer_remove_wishlist",
    ),
    path("<slugified_store_name>/address/", views.address_list, name="address_list"),
    path(
        "<slugified_store_name>/address/create/",
        views.create_address,
        name="create_address",
    ),
    path(
        "<slugified_store_name>/set-default/address/<str:id>/",
        views.set_default_address,
        name="set_default_address",
    ),
    path(
        "<slugified_store_name>/edit/address/<str:id>/",
        views.edit_address,
        name="edit_address",
    ),
    path(
        "<slugified_store_name>/delete/address/<str:id>/",
        views.delete_address,
        name="delete_address",
    ),
    path("my-stores/", views.customer_stores, name="customer_stores"),
    path("<slugified_store_name>/delete", views.delete_account, name="delete_account"),
    path(
        "<slugified_store_name>/orders/", views.customer_orders, name="customer_orders"
    ),
    path(
        "<slugified_store_name>/unpaid-orders/",
        views.unpaid_customer_orders,
        name="unpaid_customer_orders",
    ),
    path(
        "<slugified_store_name>/order/<uuid:pk>/",
        views.customer_order_detail,
        name="customer_order_detail",
    ),
    path(
        "<slugified_store_name>/reviews/",
        views.customer_reviews,
        name="customer_reviews",
    ),
    path(
        "<slugified_store_name>/review/<str:pk>/",
        views.customer_review_detail,
        name="customer_review_detail",
    ),
    path(
        "<slugified_store_name>/review/edit/<str:pk>",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "<slugified_store_name>/review/delete/<str:pk>",
        views.delete_review,
        name="delete_review",
    ),
    path(
        "<slugified_store_name>/delete/unpaid-order/<str:pk>/",
        views.delete_unpaid_order,
        name="delete_unpaid_order",
    ),
]

subscriptions/urls.py
from django.urls import path

from . import views

app_name = "subscriptions"

urlpatterns = [
    path(
        "initiate/<str:pk>",
        views.initiate_subscription_payment,
        name="initiate_subscription_payment",
    ),
    path(
        "verify/<str:ref>/",
        views.verify_subscription_payment,
        name="verify_subscription_payment",
    ),
    path(
        "cancel-recurring-subscription/",
        views.cancel_recurring_subscription,
        name="cancel_recurring_subscription",
    ),
    path(
        "activate-recurring-subscription/",
        views.activate_recurring_subscription,
        name="activate_recurring_subscription",
    ),
]

customer/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from account.models import *

# Create your models here.


class Customer(models.Model):
    full_name = models.CharField(max_length=300)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=300)
    password2 = models.CharField(max_length=300)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name="customer")
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Address(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    customer = models.ForeignKey(
        Customer, verbose_name=_("Customer"), on_delete=models.CASCADE
    )
    postcode = models.CharField(_("Postcode"), max_length=50, blank=True, null=True)
    address_line = models.CharField(_("Address Line 1"), max_length=255)
    address_line2 = models.CharField(
        _("Address Line 2"), max_length=255, blank=True, null=True
    )
    delivery_instructions = models.CharField(
        _("Delivery Instructions"), max_length=255, blank=True, null=True
    )
    country = models.CharField(_("Country"), max_length=200)
    state = models.CharField(_("State"), max_length=200)
    default = models.BooleanField(_("Default"), default=False)
    country_code = models.CharField(max_length=10, blank=True, null=True)  
    state_code = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.address_line

customer/forms.py
from django import forms
from django.forms import ModelForm
from django.shortcuts import get_object_or_404, redirect, render

from account.models import User

from .models import *


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ["full_name", "email", "password", "password2"]

        widgets = {
            "full_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Full Name"}
            ),
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Email"}
            ),
            "password": forms.PasswordInput(
                attrs={"class": "form-control", "placeholder": "Password"}
            ),
            "password2": forms.PasswordInput(
                attrs={"class": "form-control", "placeholder": "Confirm Password"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)


class ExistingUserCustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ["email"]

        widgets = {
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Email"}
            ),
        }

        def __init__(self, *args, **kwargs):
            super(ExistingUserCustomerForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data["email"]
        user = User.objects.filter(email=email)
        if not user:
            raise forms.ValidationError("User does not exist")
        return email


class AddressForm(ModelForm):
    class Meta:
        model = Address
        exclude = ["customer"]

        widgets = {
            "full_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Full Name"}
            ),
            "phone": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "+349 0854 9885"}
            ),
            "postcode": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Post Code"}
            ),
            "address_line": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Address Line"}
            ),
            "address_line2": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Additional address(Not Compulsory)",
                }
            ),
            "delivery_instructions": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Delivery Instructions"}
            ),
            "country": forms.Select(attrs={"class": "form-control"}),
            "state": forms.Select(attrs={"class": "form-control"}),
        }

app/templates/store/all-shipping-company.html
{% extends 'navs/store-nav.html' %} {% load static %}{% load humanize %}{% block title %}<title>
 Shopit - {{store }} Logistics Company
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  {% include 'navs/store-side-nav.html' %}
  <div class="store-content-container">
    <span class="store-products-container">
      <p>Logistics Company</p>
  
    {% if messages %} {% for message in messages %} {% if message %}
    <small class="error">{{message}}</small>
    {% endif %} {% endfor %} {% endif %}
      {% if request.user.is_superuser %}
      <span ><a href="{% url 'app:add_shipping_company' %}">Add Logistics Company</a></span>
      <div class="table-container">
        <table class="store-products-table">
        <tr class="table-rows">
          <th>Name</th>
          <th>Email</th>
          <th>Account Number</th>
          <th>Account Name</th>
          <th>Account Bank</th>
          <th>Bank Code</th>
          <th>Delete</th>
        </tr>
        {% for company in shipping_companies %}
        <tr class="table-rows">
          <td>
            <a href="{% url 'app:edit_shipping_company' company.pk %}">{{company.name}}</a>
          </td>
          <td>{{company.email}}</td>
          <td>{{company.account_number}}</td>
          <td>{{company.account_name}}</td>
          <td>{{company.bank_name}}</td>
          <td>{{company.bank_code}}</td>
          <td>
             <button type="button" class="delete-btn">
              <a href="{% url 'app:delete_shipping_company' company.pk %}"><i class="fas fa-trash-alt"></i>Delete</a>
            </button>
          </td>
        </tr>
        {% endfor %}
      </table>
      </div>

      {% if shipping_companies.has_other_pages %}
      <span class="pagination">
        <span>
          {% for i in shipping_companies.paginator.page_range %} {% if shipping_companies.number == i %} Showing
          {{shipping_companies.start_index }} of {{ shipping_companies.end_index }} of {{ shipping_companies.paginator.count }} 
          entries {% endif %} {% endfor %}
        </span>

        <span>
          {% if reviews.has_previous %}
          <a href="?page={{ shipping_companies.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-left disable"></i></span>
          {% endif %} {% if shipping_companies.has_next %}
          <a href="?page={{ shipping_companies.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-right disable"></i></span>
          {% endif %}
        </span>
      </span>
      {% endif %}
      {% endif %}
    </span>
  </div>
 
</div>
 {% endblock %}

app/templates/store/category.html
{% extends 'navs/store-nav.html' %} {% load static %}{% block title %}<title>
 Shopit - {{request.user }} Products
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  {% include 'navs/store-side-nav.html' %}
  <div class="store-content-container">
    <span class="store-products-container">
      <p>All Category</p>
      <span ><a href="{% url 'app:create_category' %}">Add Category</a></span>
      <div class="table-container">
        <table class="store-products-table">
        <tr class="table-rows">
          <th>Name</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        {% for category in categories %}
        <tr class="table-rows">
          <td><a href="{{category.get_absolute_url}}">{{ category.name }}</a></td>
          <td>
            <button type="button" class="update-btn">
              <a href="{% url 'app:edit_category' category.slug  %}"><i class="far fa-edit"></i>Update</a>
            </button>
          </td>
          <td>
            <button type="button" class="delete-btn">
              <a href="{% url 'app:delete_category' category.slug  %}"><i class="fas fa-trash-alt"></i>Delete</a>
            </button>
          </td>
        </tr>
        {% endfor %}
      </table>
      </div>

      {% if categories.has_other_pages %}
      <span class="pagination">
        <span>
          {% for i in categories.paginator.page_range %} {% if categories.number == i %} Showing
          {{categories.start_index }} of {{ categories.end_index }} of {{ categories.paginator.count }} 
          entries {% endif %} {% endfor %}
        </span>

        <span>
          {% if categories.has_previous %}
          <a href="?page={{ categories.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-left disable"></i></span>
          {% endif %} {% if categories.has_next %}
          <a href="?page={{ categories.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-right disable"></i></span>
          {% endif %}
        </span>
      </span>
      {% endif %}


    </span>
  </div>
  {% endblock %}
</div>

app/templates/store/coupon.html
{% extends 'navs/store-nav.html' %} {% load static %}{% block title %}<title>
 Shopit - {{request.user }} Coupon Codes
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  {% include 'navs/store-side-nav.html' %}
  <div class="store-content-container">
    <span class="store-products-container">
      <p>Coupon Codes</p>
      {% if request.user.store_creator == True %}
      <span><a href="{% url 'app:create_coupon' %}">Add Coupon</a></span>
      {% endif %}
      <div class="table-container">
        <table class="store-products-table">
        <tr class="table-rows">
          <th>Code</th>
          <th>Percentage</th>
          <th>Created</th>
          <th>Expiry(mins)</th>
          {% if request.user.store_creator == True %}
          <th>Delete</th>
          {% endif %}
        </tr>
        {% for coupon in coupons %}
        <tr class="table-rows">
          <td>{{ coupon.code }}</td>
          <td>{{ coupon.percentage}} %</td>
          <td>{{ coupon.created_at|timesince}}</td>
          <td>{{coupon.expiry_date}} mins</td>
          {% if request.user.store_creator == True %}
          <td>
            <button type="button" class="delete-btn">
              <a href="{% url 'app:delete_coupon' coupon.pk  %}"><i class="fas fa-trash-alt"></i>Delete</a>
            </button>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </table>
      </div>

      {% if coupons.has_other_pages %}
      <span class="pagination">
        <span>
          {% for i in coupons.paginator.page_range %} {% if coupons.number == i %} Showing
          {{coupons.start_index }} of {{ coupons.end_index }} of {{ coupons.paginator.count }} 
          entries {% endif %} {% endfor %}
        </span>

        <span>
          {% if coupons.has_previous %}
          <a href="?page={{ coupons.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-left disable"></i></span>
          {% endif %} {% if coupons.has_next %}
          <a href="?page={{ coupons.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-right disable"></i></span>
          {% endif %}
        </span>
      </span>
      {% endif %}


    </span>
  </div>
  {% endblock %}
</div>

app/templates/store/store-order.html
{% extends 'navs/store-nav.html' %}{% load humanize %} {% load static %}{% block title %}<title>
 Shopit - Store {% if 'unpaid' in request.get_full_path %} Unpaid {% endif %}Orders
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  {% include 'navs/store-side-nav.html' %}
  <div class="store-content-container">
    <span class="store-products-container">
      <p>Store {% if 'unpaid' in request.get_full_path %}Unpaid{% endif %} Orders - {% if orders_count %}{{orders_count}}{% else %}0{% endif %}</p>
      <p>
          {% if 'unpaid' in request.get_full_path %}
          <a href="{% url 'app:store_orders' %}">Paid Orders</a>
          <small>Unpaid orders will be deleted after 30 days</small>
          {% else %}
          <a href="{% url 'app:unpaid_store_orders'%}">Unpaid Orders</a>
          {% endif %}
        </p>
      <div class="table-container">
        <table class="store-products-table">
        
        <tr class="table-rows">
          <th>Order Id</th>
          <th>Name</th>
          <th>Email</th>
          <th>Amount</th>
          <th>Billing Status</th>
        </tr>

        {% for order in orders %} 
        <tr class="table-rows">
          <td><a href="{% url 'app:store_order_detail' order.pk %}">{{order.id|truncatechars:12}}</a></td>
          <td>
            {% if payment.full_name %} {{ payment.full_name }} {% elif payment.order.user %}
            {{payment.order.user.full_name}} {% else %} Non user/ customer {% endif %}
          </td>
          <td>
            {% if payment.order.user %} {{ order.user.email }} {% elif payment.email %} {{ payment.email}} {% else %}
            Non user/ customer {% endif %}
          </td>
          <td>
            {{order.currency_symbol}} {% if payment.currency %} {{ payment.amount|intcomma }} {% else %} 
            {{order.amount|intcomma }} {% endif %}
          </td>
          <td>{% if order.billing_status == True %} Paid {% else %} Unpaid {% endif %}</td>
        </tr>
        {% endfor %}
      </table>
      </div>
      {% if orders.has_other_pages %}
      <span class="pagination">
        <span>
          {% for i in orders.paginator.page_range %} {% if orders.number == i %} Showing
          {{orders.start_index }} of {{ orders.end_index }} of {{ orders.paginator.count }} 
          entries {% endif %} {% endfor %}
        </span>

        <span>
          {% if orders.has_previous %}
          <a href="?page={{ orders.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-left disable"></i></span>
          {% endif %} {% if orders.has_next %}
          <a href="?page={{ orders.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-right disable"></i></span>
          {% endif %}
      </span>
      </span>
      {% endif %}
      
    </span>
  </div>
  {% endblock %}
</div>

app/templates/store/store-overview.html
{% extends 'navs/store-nav.html' %} {% load static %} 
{% block title %} <title>Shop!t - My Store</title> {% endblock %}
{% block content %}
<div class="store-page-container">
  {% include 'navs/store-side-nav.html' %}

  <div class="store-content-container">
   
    
  </div>
</div>
{% endblock %}

app/templates/store/subscription-plans.html
{% extends 'navs/store-nav.html' %}{% load humanize %} {% load static %}{% load apply_markdown %}{% block title %}<title>
  Shopit - {% if 'monthly' in request.get_full_path %} Monthly {% else %} Yearly {% endif %} Subscriptions 
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  {% include 'navs/store-side-nav.html' %}
  <div class="store-content-container">
    <span class="store-products-container" id="store-products-container">
      <p>Shopit {% if 'monthly' in request.get_full_path %} Monthly {% else %} Yearly {% endif %} Subscriptions </p>
       {% if messages %} {% for message in messages %}
    <small class="error">{{message}}</small>
    {% endfor %} {% endif %}
      <p>
          {% if 'monthly' in request.get_full_path %}
          <a href="{% url 'app:yearly_subscription_plans' %}">Yearly Subscriptions</a>
          {% else %}
          <a href="{% url 'app:monthly_subscription_plans'%}">Monthly Subscriptions</a>
          {% endif %}
        </p>

        <div class="subscription-grid-container">
            {% for plan in plans %}
            <div class="a-related-container">
               {% if store in plan.subscribers.all %}
                  <small>Actively Subscribed</small>
                  {% endif %}
                <div>
                 
                <p>{{plan.name}}</p>
                <p>{{plan.currency.symbol}}{{plan.amount|intcomma}}/ {{plan.duration}}</p>
                <div>
                    {{plan.description|convert_markdown|safe}}
                </div>
                </div>
             <a href="{% url 'subscriptions:initiate_subscription_payment' plan.id %}" class="update-btn">Subscibe Now</a>
            </div>
            {% endfor %}
        </div>
        {% if request.user.store_creator == True %}
        {% if reccuring_sub == True %}
        <p>If you want to opt out from the recurring subscription policy - <a href="{% url 'subscriptions:cancel_recurring_subscription' %}">Click</a></p>
        {% endif %}
        {% if reccuring_sub == False %}
        <p>If you want to opt in into the recurring subscription policy - <a href="{% url 'subscriptions:activate_recurring_subscription' %}">Click</a></p>
        {% endif %}
        {% endif %}
    </span>
  </div>
  {% endblock %}
</div>

app/templates/store/view-more.html
{% extends 'navs/customer-nav.html' %} {% load humanize %} {% load static %} {% block title %}
<title>{{store.store_name}}</title> {%endblock%} {% block content %}
<div class="store-page-container">
  <div>
    {% if store.store_image %}
    <img class="store-image-banner" src="{{ store.store_image.url }}" alt="" />
    {% endif %}
    <div class="store-add-review-link"><a href="{% url 'app:store_review' store.slugified_store_name %}">Add a store review</a></div>
    {% if 'category' in request.get_full_path %}
    <p>{{category.name|capfirst}} Category Products</p>
    {% else %}
    <p>Products {{products.count}}</p>
    {% endif %}
    <div class="view-store-products-container">
      <div class="view-store-products-grid">
        {% for product in products %}
        <a href="{% url 'customer:customer_product_detail' store.slugified_store_name product.slug %}">
          <span>
            <img src="{{ product.image_1.url }}" />
            <img src="{{ product.image_2.url}}" alt="">
          </span>
          <div>
            <p>{{ product.name }}</p>
            <p>
              {% if product.discount_price != product.price %}
              <span>
                <span style="text-decoration: line-through">{{product.currency.symbol}}{{ product.price|intcomma }}</span>
                <span>{{product.currency.symbol}}{{ product.discount_price|intcomma }}</span>
              </span>
              {% else %}
            </p>
            <div>{{product.currency.symbol}}{{ product.price|intcomma }}</div>
            {% endif %}
          </div>
        </a>
        {% endfor %}
      </div>
    </div>
    {% if products.has_other_pages %}
      <span class="pagination">
          {% if products.has_previous %}
          <a class="view-more-btn" href="?page={{ products.previous_page_number }}">Prev Page <i class="fas fa-arrow-left"></i></a>
          {% else %}
          <span class="view-more-btn disable">Prev Page <i class="fas fa-arrow-left disable"></i></span>
          {% endif %} {% if products.has_next %}
          <a class="view-more-btn" href="?page={{ products.next_page_number }}">Next Page <i class="fas fa-arrow-right"></i></a>
          {% else %}
          <span class="view-more-btn disable">Next Page <i class="fas fa-arrow-right"></i></span>
          {% endif %}
        </span>
      {% endif %}
  </div>
  
</div>
  {% endblock %}