app/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "app"


urlpatterns = [
    path("", views.home_page, name="base"),
    path("create-product/", views.create_product, name="create_product"),
    path("edit/product/<slug>", views.edit_product, name="edit_product"),
    path("delete/product/<slug>", views.delete_product, name="delete_product"),
    path("add-wishlist/<slug>", views.add_wishlist, name="add_wishlist"),
    path("remove-wishlist/<slug>", views.remove_wishlist, name="remove_wishlist"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wallet/", views.store_wallet, name="store_wallet"),
    path(
        "products/",
        views.a_store_all_products,
        name="store_products",
    ),
    path(
        "product/<slug:slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "store/<slugified_store_name>/category/<slug:slug>/products/",
        views.store_category_products,
        name="store_category_products",
    ),
    path(
        "store/<slugified_store_name>/collections",
        views.all_store_products,
        name="all_store_products",
    ),
    path("store/", views.store_admin, name="store_admin"),
    path("store/<slugified_store_name>/", views.store, name="store"),
    path("categories/", views.all_category, name="all_category"),
    path("create-category/", views.add_category, name="create_category"),
    path("edit-category/<slug:slug>/", views.edit_category, name="edit_category"),
    path("delete-category/<slug:slug>/", views.delete_category, name="delete_category"),
    path("discount-products/", views.discount_products, name="discount_products"),
    path("coupon/", views.all_coupons, name="all_coupons"),
    path("create-coupon/", views.create_coupon, name="create_coupon"),
    path("delete-coupon/<str:pk>/", views.delete_coupon, name="delete_coupon"),
    path("customers/", views.all_customers, name="all_customers"),
    path("orders/", views.store_orders, name="store_orders"),
    path("unpaid-orders/", views.unpaid_store_orders, name="unpaid_store_orders"),
    path("order/<uuid:pk>/", views.store_order_detail, name="store_order_detail"),
    path("<slugified_store_name>/review/", views.store_review, name="store_review"),
    path(
        "<slugified_store_name>/create/review/product/<slug:slug>/",
        views.product_store_review,
        name="product_store_review",
    ),
    path("reviews/", views.store_review_list, name="store_review_list"),
    path("review/<str:pk>/", views.store_review_detail, name="store_review_detail"),
    path(
        "yearly/subscriptions/",
        views.yearly_subscription_plans,
        name="yearly_subscription_plans",
    ),
    path(
        "monthly/subscriptions/",
        views.monthly_subscription_plans,
        name="monthly_subscription_plans",
    ),
    path(
        "transanction-history/", views.transanction_history, name="transanction_history"
    ),
    path("store-staff/", views.store_staff_page, name="store_staff_page"),
    path("shipping/", views.shipping_method_list, name="shipping_method_list"),
    path(
        "notification/mark-as-read/<str:id>/",
        views.mark_notification_read,
        name="mark_notification_read",
    ),
    path(
        "customer/detail/<str:pk>/",
        views.store_customers_details,
        name="store_customers_details",
    ),
    path(
        "store/<slugified_store_name>/product/<slug:slug>/reviews/",
        views.product_review_list,
        name="product_review_list",
    ),
    path("company/reviews/", views.company_review, name="company_review"),
    path("company/team/", views.company_team, name="company_team"),
    path("get-state/<iso2>/", views.get_state, name="get_state"),
    path("get-city/<iso2>/", views.get_state, name="get_city"),
    path("notifications/", views.notification_page, name="notification_page"),
    path("newsletter/", views.newsletter_page, name="newsletter_page"),
    path("generate/newsletter/", views.generate_store_newsletter, name="generate_store_newsletter"),
    path("draft/newsletter/", views.draft_newsletter, name="draft_newsletter"),
    path("publish/newsletter/", views.publish_newsletter, name="publish_newsletter"),
    path("publish/draft/newsletter/<str:pk>", views.publish_draft_newsletter, name="publish_draft_newsletter"),
    path("delete/newsletter/<str:pk>/", views.delete_draft_newsletter, name="delete_draft_newsletter"),
    path("edit/draft/newsletter/<str:pk>/", views.edit_draft_newsletter, name="edit_draft_newsletter"),
    path("unsubscribe-newsletter/<slugified_store_name>/", views.unsubscribe_newsletter, name="unsubscribe_newsletter"),
    path("resubscribe-newsletter/<slugified_store_name>/", views.resubscribe_newsletter, name="resubscribe_newsletter"),
    path(
        "create/shipping-method/", views.add_shipping_method, name="add_shipping_method"
    ),
    path(
        "edit/shipping-method/<str:pk>",
        views.edit_shipping_method,
        name="edit_shipping_method",
    ),
    path(
        "delete/shipping-method/<str:pk>",
        views.delete_shipping_method,
        name="delete_shipping_method",
    ),
    path("shipping-company/", views.shipping_company_list, name="shipping_company_list"),
    path("add/shipping-company/", views.add_shipping_company, name="add_shipping_company"),
    path("edit/shipping-company/<str:pk>", views.edit_shipping_company, name="edit_shipping_company"),
    path("delete/shipping-company/<str:pk>", views.delete_shipping_company, name="delete_shipping_company"),
    path("faqs/", TemplateView.as_view(template_name='faqs.html'), name="faqs" ),
    path("terms/", TemplateView.as_view(template_name='terms.html'), name="terms" ),
    path("privacy-policy/", TemplateView.as_view(template_name='privacy-policy.html'), name="privacy_policy" ),
    
]

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("<slugified_store_name>/", views.cart_summary, name="cart_summary"),
    path("<slugified_store_name>/add/", views.add_to_cart, name="add_to_cart"),
    path(
        "<slugified_store_name>/delete/",
        views.delete_from_cart,
        name="delete_form_cart",
    ),
    path("<slugified_store_name>/update/", views.update_cart, name="update_cart"),
    path(
        "<slugified_store_name>/clear-all-cart/",
        views.clear_all_cart,
        name="clear_all_cart",
    ),
]

core/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls")),
    path("customer/", include("customer.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "app.views.custom_error_404"
handler500 = "app.views.custom_error_500"

customer/urls.py
from django.urls import path

from . import views

app_name = "customer"

urlpatterns = [
    path(
        "register/<slugified_store_name>/",
        views.customer_register,
        name="customer_register",
    ),
    path(
        "login/<slug:slugified_store_name>/",
        views.customer_login,
        name="customer_login",
    ),
    path(
        "logout/<slugified_store_name>/", views.customer_logout, name="customer_logout"
    ),
    path(
        "register/existing-user/<slugified_store_name>/",
        views.existing_user_customer_register,
        name="existing_user_customer_register",
    ),
    path(
        "<slugified_store_name>/logout", views.customer_logout, name="customer_logout"
    ),
    path(
        "<slugified_store_name>/product/<slug:slug>/",
        views.customer_product_detail,
        name="customer_product_detail",
    ),
    path(
        "<slugified_store_name>/profile/",
        views.customer_profile,
        name="customer_profile",
    ),
    path(
        "<slugified_store_name>/wishlist/",
        views.customer_wishlist,
        name="customer_wishlist",
    ),
    path(
        "add-wishlist/<slug>", views.customer_add_wishlist, name="customer_add_wishlist"
    ),
    path(
        "remove-wishlist/<slug>",
        views.customer_remove_wishlist,
        name="customer_remove_wishlist",
    ),
    path("<slugified_store_name>/address/", views.address_list, name="address_list"),
    path(
        "<slugified_store_name>/address/create/",
        views.create_address,
        name="create_address",
    ),
    path(
        "<slugified_store_name>/set-default/address/<str:id>/",
        views.set_default_address,
        name="set_default_address",
    ),
    path(
        "<slugified_store_name>/edit/address/<str:id>/",
        views.edit_address,
        name="edit_address",
    ),
    path(
        "<slugified_store_name>/delete/address/<str:id>/",
        views.delete_address,
        name="delete_address",
    ),
    path("my-stores/", views.customer_stores, name="customer_stores"),
    path("<slugified_store_name>/delete", views.delete_account, name="delete_account"),
    path(
        "<slugified_store_name>/orders/", views.customer_orders, name="customer_orders"
    ),
    path(
        "<slugified_store_name>/unpaid-orders/",
        views.unpaid_customer_orders,
        name="unpaid_customer_orders",
    ),
    path(
        "<slugified_store_name>/order/<uuid:pk>/",
        views.customer_order_detail,
        name="customer_order_detail",
    ),
    path(
        "<slugified_store_name>/reviews/",
        views.customer_reviews,
        name="customer_reviews",
    ),
    path(
        "<slugified_store_name>/review/<str:pk>/",
        views.customer_review_detail,
        name="customer_review_detail",
    ),
    path(
        "<slugified_store_name>/review/edit/<str:pk>",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "<slugified_store_name>/review/delete/<str:pk>",
        views.delete_review,
        name="delete_review",
    ),
    path(
        "<slugified_store_name>/delete/unpaid-order/<str:pk>/",
        views.delete_unpaid_order,
        name="delete_unpaid_order",
    ),
]

app/templates/product/a-user-all-categories.html
{% extends 'navs/base.html' %}
{% load static %}

{% block content %}
{% endblock %}

app/templates/product/a-user-all-products.html
{% extends 'navs/base.html' %}
{% load static %}
{% block content %}
{% endblock %}

app/templates/product/discount-products.html
{% extends 'navs/store-nav.html' %} {% load humanize %} {% load static %}{% block title %}<title>
 Shopit - {{request.user }} Discount Products
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  {% include 'navs/store-side-nav.html' %}
  <div class="store-content-container">
    <span class="store-products-container">
      <p>Discount Products</p>
      <div class="table-container">
        <table class="store-products-table">
        <tr class="table-rows">
          <th>Product</th>
          <th>Price</th>
          <th>Discount</th>
          <th>Discount Price</th>
        </tr>
        {% for product in products %}
        <tr class="table-rows">
          <td><a href="{{product.get_absolute_url}}">{{ product.name }}</a></td>
          <td>{{store.currency.symbol}}{{ product.price|intcomma }}</td>
          <td>{{ product.discount_percentage }} %</td>
          <td>{{store.currency.symbol}}{{product.discount_price|intcomma }}</td>
        </tr>
        {% endfor %}
      </table>
      </div>

      {% if products.has_other_pages %}
      <span class="pagination">
        <span>
          {% for i in products.paginator.page_range %} {% if products.number == i %} Showing
          {{products.start_index }} of {{ products.end_index }} of {{ products.paginator.count }} 
          entries {% endif %} {% endfor %}
        </span>

        <span>
          {% if products.has_previous %}
          <a href="?page={{ products.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-left disable"></i></span>
          {% endif %} {% if products.has_next %}
          <a href="?page={{ products.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-right disable"></i></span>
          {% endif %}
        </span>
      </span>
      {% endif %}

    </span>
  </div>
  {% endblock %}
</div>

app/templates/product/product-detail.html
{% extends 'navs/customer-nav.html' %} {% load humanize %}{% load static %}{% load humanize %}
{% block title %}<title>
 Shopit - {{product.created_by}} {{product.name}}
</title>
{% endblock %} {% block content %}

<div class="product-container">
  <form class="wallet-withdrawal-form"   id="withdrawal-naira-form" action="">
            <div class="above-create-form" id="above-create-form">
                <p>Shopit Warning</p>
            </div>
            <div class="input-container" id="input-container">
              
                <div id="amount">
                  You can not order more than the available quantity
                </div>
            </div>
            <div class="form-btn-container" id="form-btn-container">
            <div class="form-btn" id="form-btn">
            ok
            </div>
            </div> 
            </form>
  <div class="carousel">
    <button class="carousel__button carousel__button--left is-hidden">
      <img src="{% static 'images/icons/arrow-left-solid.svg' %}" alt="" />
    </button>
    <div class="carousel__track-container">
      <ul class="carousel__track">
        {% if product.image_1 %}
        <li class="carousel__slide currentSlide">
          <img class="carousel__image" src="{{product.image_1.url}}" alt="" />
        </li>
        {% endif %} {% if product.image_2 %}
        <li class="carousel__slide">
          <img class="carousel__image" src="{{product.image_2.url}}" alt="" />
        </li>
        {% endif %} {% if product.image_3 %}
        <li class="carousel__slide">
          <img class="carousel__image" src="{{product.image_3.url}}" alt="" />
        </li>
        {% endif %} {% if product.image_4 %}
        <li class="carousel__slide">
          <img class="carousel__image" src="{{product.image_4.url}}" alt="" />
        </li>
        {% endif %}
      </ul>
    </div>
    <button class="carousel__button carousel__button--right">
      <img src="{% static 'images/icons/arrow-right-solid.svg' %}" alt="" />
    </button>

    <div class="carousel__nav">
      {% if product.image_1 %}
      <button class="carousel__indicator current-slide"></button>
      {% endif %} {% if product.image_2 %}
      <button class="carousel__indicator"></button>
      {% endif %} {% if product.image_3 %}
      <button class="carousel__indicator"></button>
      {% endif %} {% if product.image_4 %}
      <button class="carousel__indicator"></button>
      {% endif %}
    </div>
  </div>

  <div class="product-info">
    <h1>{{ product.name }}</h1>
    <a href="{{product.category.get_absolute_url}}">{{product.category}}</a>
    <p>{{product.description}}</p>
   
    <div>
      {% if product.availability > 1 %}
    <span>Availability: <span id="product-availability">{{product.availability}}</span> {{product.product_unit}}s</span>
    {% else %}
    <span>Availability: <span id="product-availability">{{product.availability}}</span> {{product.product_unit}}</span>
    {% endif %}
    </div>

    <div class="">
      {% if product.discount_percentage %}
      <span>{{product.currency.symbol}}{{product.discount_price|intcomma }}</span>
      <span class="discount-precentage">{{product.discount_percentage|intcomma }}%</span>
      <p class="price-with-discount">{{product.currency.symbol}}{{product.price|intcomma }}</p>
      {% else %}
      <span><b>{{product.currency.symbol}}{{product.price|intcomma }}</b></span>
      {% endif %}
    </div>
  
  
      {% if product.availability > 0 %}
    <div style="width: 150px;">
      <input type="number" name="product-order-count" id="product-order-count" class="form-control" placeholder="Enter quantity" value="">
    </div>

    <button type="button" id="add-to-cart-btn" value="{{product.id}}" class="update-btn">Add to cart</button>
    {% else %}
    <button type="button" id="add-to-cart-btn" value="{{product.id}}" class="update-btn out-of-stock">
      Out of stock
    </button>
    {% endif %}

    {% if request.user.is_authenticated %}
        {% if request.user in product.wishlist.all %}
        {% if 'customer' in request.get_full_path %}
        <button type="button" class="delete-btn"><a href="{% url 'customer:customer_remove_wishlist' product.slug %}">Remove from WishList</a></button>
        {% else %}
       <button type="button" class="delete-btn"><a href="{% url 'app:remove_wishlist' product.slug %}">Remove from WishList</a></button>
       {% endif %}
        {% else %}
        {% if 'customer' in request.get_full_path %}
        <button type="button" class="update-btn"><a href="{% url 'customer:customer_add_wishlist' product.slug %}">Add to WishList</a></button>
        {% else %}
         <button type="button" class="update-btn"><a href="{% url 'app:add_wishlist' product.slug %}">Add to WishList</a></button>
         {% endif %}
        {% endif %}
    {% endif %}
  

    {% if product.product_details %}
    <div>
      <h3>Product Details</h3>
      <p>{{product.product_details|safe}}</p>
    </div>
    {% endif %}
    <div class="reviews">
      <h2>Reviews</h2>
      <a href="{% url 'app:product_store_review' store.slugified_store_name product.slug %}" class="add-review-link">Add a product review</a>
      {% for review in reviews %}
     <ul>
      <li>
        {% if review.store.store_name == request.user.store_name or request.user in store.staffs %}
        <a href="{% url 'app:store_review_detail' review.pk %}">{{ review.title|truncatechars:40}}</a>
        {% else %}
        <a href="{% url 'customer:customer_review_detail' slugified_store_name=review.store.slugified_store_name pk=review.pk %}">{{ review.title|truncatechars:40}}</a>
        {% endif %}
        <p><span>{{review.full_name}}</span> - <span>{{review.created|timesince}}</span></p>
      </li>
     </ul>
      {% endfor %}
      {% if reviews.count == 2 %}
      <a class="view-more-btn" href="{% url 'app:product_review_list' slugified_store_name=store.slugified_store_name slug=product.slug %}">View More</a>
      {% endif %}
    </div>
    </div>
  
  </div>
</div>

{% if category_product %}
<div class="related-product-sec">
  <p>You might also like</p>
  <div class="related-products-container">
    {% for product in category_product %}
    <a class="a-related-container" href="{{product.get_absolute_url}}">
      <span class="product-image-container">
        <img src="{{product.image_1.url}}" alt="" />
      </span>
      <div class="product-info-container">
        <p>{{ product.name }}</p>
        <p>
            {% if product.discount_price != product.price %}
              <span>
                <span style="text-decoration: line-through">{{product.currency.symbol}}{{ product.price|intcomma }}</span>
                <span>{{product.currency.symbol}}{{ product.discount_price|intcomma }}</span>
              </span>
              {% else %}
            </p>
            <div>{{product.currency.symbol}}{{ product.price|intcomma }}</div>
            {% endif %}
      </div>
    </a>
    {% endfor %}
  </div>
  {% if category_product.count > 6 %}
  <a class="view-more-btn" href="">View more</a>
  {% endif %}
</div>
{% endif %}
<script>

  const availability = document.getElementById('product-availability').innerText;
 

  $(document).on("click", "#add-to-cart-btn", function (e) {
    $.ajax({
      type: "POST",
      url: "{% url 'cart:add_to_cart' store.slugified_store_name %}",
      data: {
        productid: $("#add-to-cart-btn").val(),
        productqty: (parseInt($("#product-order-count").val()) > parseInt(availability)) ? availability : $("#product-order-count").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
        action: "post",
      },

      success: function (json) {
        document.getElementById("product-cart-qty").innerHTML = json.qty;
        const productOrderCount = ($("#product-order-count").val() > parseInt(availability)) ? availability : $("#product-order-count").val();
        $("#product-order-count").val(productOrderCount);

      },
      error: function (xhr, errmsg, err) {},
    });

    const myavailability = $("#product-availability").text();
    const productOrderCount = ($("#product-order-count").val());
    const errorAlert = $("#withdrawal-naira-form");
    const minWidth = window.matchMedia("(min-width: 990px)");
    const addToCartBtn = $("#add-to-cart-btn");
    const errorAlertBtn = $("#form-btn");
    const nav = $("#nav");
    const cartIconContainer = $("#cart-icon-container");


    if (parseInt(productOrderCount) > parseInt(myavailability)) {
      $("#product-order-count").val(myavailability);
      errorAlert.addClass("active");
      errorAlertBtn.css("width", "max-content");
      addToCartBtn.addClass("disable");
      errorAlert.css("z-index", "1071");
      nav.css("z-index", "10");
      errorAlert.css("position", "fixed");
      if (cartIconContainer) {
        cartIconContainer.addClass("disable");
      }
      if (minWidth.matches) {
        errorAlert.css("top", "19%");
      } else {
         errorAlert.css("top", "22%");
      }     
    } else {
      $("#product-order-count").val(productOrderCount);
    }
  });

  $(document).on("click", "#form-btn", function (e) {
    $("#withdrawal-naira-form").removeClass("active");
    $("#add-to-cart-btn").removeClass("disable");
    if ($("#cart-icon-container")) {
        $("#cart-icon-container").removeClass("disable");
      }
  });


</script>
<script src="{% static 'js/carousel.js' %}"></script>
{% endblock %}
