account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PasswordResetConfirmForm, PasswordResetForm

app_name = "account"

urlpatterns = [
    path(
        "activate/<slug:uidb64>/<slug:token>)/",
        views.account_activate,
        name="activate_account",
    ),
    path("register/", views.account_register, name="register"),
    path("login/", views.account_login, name="login"),
    path("logout/", views.account_logout, name="logout"),
    path("settings/profile/", views.user_profile, name="user_profile"),
    path("settings/store-account/", views.store_account, name="store_account"),
    path("delete/", views.account_delete, name="delete_account"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/user/password-reset-form.html",
            success_url="password-reset-email-confirm",
            email_template_name="account/user/password-reset-email.html",
            form_class=PasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/user/password-reset-confirm.html",
            success_url="/account/password-reset-complete/",
            form_class=PasswordResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/password-reset-email-confirm/",
        TemplateView.as_view(template_name="account/user/password-reset-success.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        TemplateView.as_view(template_name="account/user/password-reset-success.html"),
        name="password_reset_complete",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/user/forgot-password.html", success_url="/"
        ),
        name="change_password",
    ),
    path(
        "store/<slugified_store_name>/add-store-staff/",
        views.store_staff_register,
        name="store_staff_register",
    ),
    path("delete-staff/<str:pk>", views.delete_store_staff, name="delete_store_staff"),
    path("staff-stores/", views.staff_stores, name="staff_stores"),
    path("store/<slugified_store_name>/", views.select_store, name="select_store"),
    path("add-staff/user/", views.add_store_staff, name="add_store_staff"),
    path("create-store/", views.create_store, name="create_store"),
    path("bank-details/", views.bank_details, name="bank_details"),
    path(
        "store/<slug:slugified_store_name>/accept-invitation/<str:email>/<slug:uidb64>/<slug:token>/",
        views.accept_staff_invitation,
        name="accept_staff_invitation",
    ),
    path("bank-auth/<slug:uidb64>/<slug:token>/<account_number>/<account_name>/<bank_name>/<bank_code>/", views.bank_auth, name="bank_auth"),
]

app/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "app"


urlpatterns = [
    path("", views.home_page, name="base"),
    path("create-product/", views.create_product, name="create_product"),
    path("edit/product/<slug>", views.edit_product, name="edit_product"),
    path("delete/product/<slug>", views.delete_product, name="delete_product"),
    path("add-wishlist/<slug>", views.add_wishlist, name="add_wishlist"),
    path("remove-wishlist/<slug>", views.remove_wishlist, name="remove_wishlist"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wallet/", views.store_wallet, name="store_wallet"),
    path(
        "products/",
        views.a_store_all_products,
        name="store_products",
    ),
    path(
        "product/<slug:slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "store/<slugified_store_name>/category/<slug:slug>/products/",
        views.store_category_products,
        name="store_category_products",
    ),
    path(
        "store/<slugified_store_name>/collections",
        views.all_store_products,
        name="all_store_products",
    ),
    path("store/", views.store_admin, name="store_admin"),
    path("store/<slugified_store_name>/", views.store, name="store"),
    path("categories/", views.all_category, name="all_category"),
    path("create-category/", views.add_category, name="create_category"),
    path("edit-category/<slug:slug>/", views.edit_category, name="edit_category"),
    path("delete-category/<slug:slug>/", views.delete_category, name="delete_category"),
    path("discount-products/", views.discount_products, name="discount_products"),
    path("coupon/", views.all_coupons, name="all_coupons"),
    path("create-coupon/", views.create_coupon, name="create_coupon"),
    path("delete-coupon/<str:pk>/", views.delete_coupon, name="delete_coupon"),
    path("customers/", views.all_customers, name="all_customers"),
    path("orders/", views.store_orders, name="store_orders"),
    path("unpaid-orders/", views.unpaid_store_orders, name="unpaid_store_orders"),
    path("order/<uuid:pk>/", views.store_order_detail, name="store_order_detail"),
    path("<slugified_store_name>/review/", views.store_review, name="store_review"),
    path(
        "<slugified_store_name>/create/review/product/<slug:slug>/",
        views.product_store_review,
        name="product_store_review",
    ),
    path("reviews/", views.store_review_list, name="store_review_list"),
    path("review/<str:pk>/", views.store_review_detail, name="store_review_detail"),
    path(
        "yearly/subscriptions/",
        views.yearly_subscription_plans,
        name="yearly_subscription_plans",
    ),
    path(
        "monthly/subscriptions/",
        views.monthly_subscription_plans,
        name="monthly_subscription_plans",
    ),
    path(
        "transanction-history/", views.transanction_history, name="transanction_history"
    ),
    path("store-staff/", views.store_staff_page, name="store_staff_page"),
    path("shipping/", views.shipping_method_list, name="shipping_method_list"),
    path(
        "notification/mark-as-read/<str:id>/",
        views.mark_notification_read,
        name="mark_notification_read",
    ),
    path(
        "customer/detail/<str:pk>/",
        views.store_customers_details,
        name="store_customers_details",
    ),
    path(
        "store/<slugified_store_name>/product/<slug:slug>/reviews/",
        views.product_review_list,
        name="product_review_list",
    ),
    path("company/reviews/", views.company_review, name="company_review"),
    path("company/team/", views.company_team, name="company_team"),
    path("get-state/<iso2>/", views.get_state, name="get_state"),
    path("get-city/<iso2>/", views.get_state, name="get_city"),
    path("notifications/", views.notification_page, name="notification_page"),
    path("newsletter/", views.newsletter_page, name="newsletter_page"),
    path("generate/newsletter/", views.generate_store_newsletter, name="generate_store_newsletter"),
    path("draft/newsletter/", views.draft_newsletter, name="draft_newsletter"),
    path("publish/newsletter/", views.publish_newsletter, name="publish_newsletter"),
    path("publish/draft/newsletter/<str:pk>", views.publish_draft_newsletter, name="publish_draft_newsletter"),
    path("delete/newsletter/<str:pk>/", views.delete_draft_newsletter, name="delete_draft_newsletter"),
    path("edit/draft/newsletter/<str:pk>/", views.edit_draft_newsletter, name="edit_draft_newsletter"),
    path("unsubscribe-newsletter/<slugified_store_name>/", views.unsubscribe_newsletter, name="unsubscribe_newsletter"),
    path("resubscribe-newsletter/<slugified_store_name>/", views.resubscribe_newsletter, name="resubscribe_newsletter"),
    path(
        "create/shipping-method/", views.add_shipping_method, name="add_shipping_method"
    ),
    path(
        "edit/shipping-method/<str:pk>",
        views.edit_shipping_method,
        name="edit_shipping_method",
    ),
    path(
        "delete/shipping-method/<str:pk>",
        views.delete_shipping_method,
        name="delete_shipping_method",
    ),
    path("shipping-company/", views.shipping_company_list, name="shipping_company_list"),
    path("add/shipping-company/", views.add_shipping_company, name="add_shipping_company"),
    path("edit/shipping-company/<str:pk>", views.edit_shipping_company, name="edit_shipping_company"),
    path("delete/shipping-company/<str:pk>", views.delete_shipping_company, name="delete_shipping_company"),
    path("faqs/", TemplateView.as_view(template_name='faqs.html'), name="faqs" ),
    path("terms/", TemplateView.as_view(template_name='terms.html'), name="terms" ),
    path("privacy-policy/", TemplateView.as_view(template_name='privacy-policy.html'), name="privacy_policy" ),
    
]

cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("<slugified_store_name>/", views.cart_summary, name="cart_summary"),
    path("<slugified_store_name>/add/", views.add_to_cart, name="add_to_cart"),
    path(
        "<slugified_store_name>/delete/",
        views.delete_from_cart,
        name="delete_form_cart",
    ),
    path("<slugified_store_name>/update/", views.update_cart, name="update_cart"),
    path(
        "<slugified_store_name>/clear-all-cart/",
        views.clear_all_cart,
        name="clear_all_cart",
    ),
]

core/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls")),
    path("customer/", include("customer.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "app.views.custom_error_404"
handler500 = "app.views.custom_error_500"

customer/urls.py
from django.urls import path

from . import views

app_name = "customer"

urlpatterns = [
    path(
        "register/<slugified_store_name>/",
        views.customer_register,
        name="customer_register",
    ),
    path(
        "login/<slug:slugified_store_name>/",
        views.customer_login,
        name="customer_login",
    ),
    path(
        "logout/<slugified_store_name>/", views.customer_logout, name="customer_logout"
    ),
    path(
        "register/existing-user/<slugified_store_name>/",
        views.existing_user_customer_register,
        name="existing_user_customer_register",
    ),
    path(
        "<slugified_store_name>/logout", views.customer_logout, name="customer_logout"
    ),
    path(
        "<slugified_store_name>/product/<slug:slug>/",
        views.customer_product_detail,
        name="customer_product_detail",
    ),
    path(
        "<slugified_store_name>/profile/",
        views.customer_profile,
        name="customer_profile",
    ),
    path(
        "<slugified_store_name>/wishlist/",
        views.customer_wishlist,
        name="customer_wishlist",
    ),
    path(
        "add-wishlist/<slug>", views.customer_add_wishlist, name="customer_add_wishlist"
    ),
    path(
        "remove-wishlist/<slug>",
        views.customer_remove_wishlist,
        name="customer_remove_wishlist",
    ),
    path("<slugified_store_name>/address/", views.address_list, name="address_list"),
    path(
        "<slugified_store_name>/address/create/",
        views.create_address,
        name="create_address",
    ),
    path(
        "<slugified_store_name>/set-default/address/<str:id>/",
        views.set_default_address,
        name="set_default_address",
    ),
    path(
        "<slugified_store_name>/edit/address/<str:id>/",
        views.edit_address,
        name="edit_address",
    ),
    path(
        "<slugified_store_name>/delete/address/<str:id>/",
        views.delete_address,
        name="delete_address",
    ),
    path("my-stores/", views.customer_stores, name="customer_stores"),
    path("<slugified_store_name>/delete", views.delete_account, name="delete_account"),
    path(
        "<slugified_store_name>/orders/", views.customer_orders, name="customer_orders"
    ),
    path(
        "<slugified_store_name>/unpaid-orders/",
        views.unpaid_customer_orders,
        name="unpaid_customer_orders",
    ),
    path(
        "<slugified_store_name>/order/<uuid:pk>/",
        views.customer_order_detail,
        name="customer_order_detail",
    ),
    path(
        "<slugified_store_name>/reviews/",
        views.customer_reviews,
        name="customer_reviews",
    ),
    path(
        "<slugified_store_name>/review/<str:pk>/",
        views.customer_review_detail,
        name="customer_review_detail",
    ),
    path(
        "<slugified_store_name>/review/edit/<str:pk>",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "<slugified_store_name>/review/delete/<str:pk>",
        views.delete_review,
        name="delete_review",
    ),
    path(
        "<slugified_store_name>/delete/unpaid-order/<str:pk>/",
        views.delete_unpaid_order,
        name="delete_unpaid_order",
    ),
]

app/templates/navs/customer-nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css'%}" />
    <link rel="stylesheet" href="{% static 'css/carousel.css'%}" />
    <link rel="stylesheet" href="{% static 'css/mobile-view.css'%}" />
    <link rel="stylesheet" href="{% static 'css/desktop-view.css'%}" />
    <link rel="stylesheet" href="{% static 'css/ckeditor-cleaning.css'%}" />
    <link rel="shortcut icon" href="{% static 'images/logo/favicon.svg' %}" type="image/x-icon">
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    {% block title %}
    <title>Shop !t</title>
    {% endblock %}

    {% if SEO == True %}
    {% include 'navs/SEO.html' %}
    {% endif %}
  </head>
  <body>
    <nav class="nav" id="nav">
      <span class="store-nav-logo">
        {% if store.store_image %}
        <span>
          {% if request.user.store_creator == True or request.user.store_staff == True %}
          <a  href="{% url 'app:store_admin' %}"><img src="{{store.store_image.url}}" alt=""></a>
          {% else %}
          <a href="{% url 'app:store' store.slugified_store_name%}"><img src="{{store.store_image.url}}" alt=""></a>
          {% endif %}
        </span>
        {% else %}
        <a href="{% url 'app:store' store.slugified_store_name %}">{{store.store_name|upper}}</a>
        {% endif %}
      </span>

      <ul id="nav-links">
        <span class="cart-icon-container cart-mobile">
          <a href="{% url 'cart:cart_summary' store.slugified_store_name %}" class="cart-btn">
            {% with total_qty=cart|length %}
            <span id="product-cart-qty">
              <span class="cart-qty-num">
                {% if total_qty > 0 %}
                <div class="cart-qty-num">{{ total_qty }}</div>
                {% else %}
                <div class="cart-qty-num">0</div>
                {% endif %}
              </span>

              {% endwith %}
            </span>
            <i class="far fa-shopping-cart"></i>
          </a>
        </span>

          <input type="text" id="side-nav-search-bar-customer" class="side-nav-search-bar customer-search-bar"  
          {% if 'store' and 'category' in request.get_full_path %}
          placeholder="Search for {{get_store_category}} Category Products" 
          {% elif 'customer' in request.get_full_path %}
           placeholder="Search for orders and reviews" 
          {% else %}
          placeholder="Search for Products" 
          {% endif %}

          onkeyup="myFunction()" onclick="customerSearchBar()"/>
          <ul id="search-display" class="customer-search-display">

      
            
            {% if get_store_category_products %}
            {% for product in get_store_category_products %}
            <li><a href="{% url 'app:product_detail' product.slug %}">{{product.name}}</a></li>
            {% endfor %}
            {% endif %}
            
          
         
            {% if get_store_products %}
            {% for product in get_store_products %}
            <li><a href="{% url 'app:product_detail' product.slug %}">{{product.name}}</a></li>
            {% endfor %}
            {% endif %}



            {% if get_customer_orders %}
            {% for order in get_customer_orders %}
            <li><a href="{% url 'customer:customer_order_detail' order.id %}">{{order.id}}</a></li>
            {% endfor %}
            {% endif %}
           

            {% if get_customer_reviews %}
            {% for review in get_customer_reviews %}
            <li><a href="{% url 'customer:customer_review_detail' review.id %}">{{review.title}}</a></li>
            {% endfor %}
            {% endif %}
       
            

          </ul>

      

        <span class="cart-icon-container cart-desktop" id="cart-icon-container">
          <a href="{% url 'cart:cart_summary' store.slugified_store_name %}" class="cart-btn">
            {% with total_qty=cart|length %}
            <span>
              <span  class="cart-qty-num">
                {% if total_qty > 0 %}
                <div id="product-cart-qty" class="cart-qty-num">{{ total_qty }}</div>
                {% else %}
                <div class="cart-qty-num">0</div>
                {% endif %}
              </span>

              {% endwith %}
            </span>
            <i class="far fa-shopping-cart"></i>
          </a>
        </span>
        {% if store %} 
        <span>
          <li>
            <a href="{% url 'app:store_review' store.slugified_store_name %}">Add a store review</a>
          </li>
        </span>
        {% if request.user in store.customers.all %}
        <li>
          <a href="{% url 'customer:customer_profile' store.slugified_store_name %}" id="a-nav-link">My Account</a>
        </li>
        <span>
          <li><a href="{% url 'customer:customer_wishlist' store.slugified_store_name %}">My Wishlist</a></li>
          <li><a href="{% url 'customer:customer_orders' store.slugified_store_name %}">Order</a></li>
          <li><a href="{% url 'customer:customer_reviews' store.slugified_store_name %}">Reviews</a></li>
          <li><a href="{% url 'customer:address_list' store.slugified_store_name%}">Address</a></li>
          <li><a href="{% url 'customer:customer_logout' store.slugified_store_name %}">Sign Out</a></li>
        </span>
        {% else %} {% if owner_store == store %} {% else %}
        <li><a href="{% url 'customer:customer_login' store.slugified_store_name %}" id="a-nav-link">Sign In</a></li>
        <li><a href="{% url 'customer:customer_register' store.slugified_store_name %}" id="a-nav-link">Sign Up</a></li>
        {% endif %} {% endif %} {% endif %}
      </ul>

      

      <div id="toogle"></div>
    </nav>
    <div class="main-container-large">{% block content %} {% endblock %}</div>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/templates/navs/store-nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'images/logo/favicon.svg' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/styles.css'%}" />
    <link rel="stylesheet" href="{% static 'css/carousel.css'%}" />
    <link rel="stylesheet" href="{% static 'css/mobile-view.css'%}" />
    <link rel="stylesheet" href="{% static 'css/desktop-view.css'%}" />
    <link rel="stylesheet" href="{% static 'css/ckeditor-cleaning.css'%}" />
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    {% block title %}
    <title>{{a_staff_store_store}}</title>
    {% endblock %}
    {% if SEO == True %}
    {% include 'navs/SEO.html' %}
    {% endif %}
  </head>
  <body id="body">
    <nav class="store-nav" id="nav">
      <span class="store-nav-logo">
        {% if a_staff_store_store.store_image %}
        <span>
          <a href="{% url 'app:store_admin' %}">
            <img src="{{a_staff_store_store.store_image.url}}" alt="">
            </a>
        </span>
        {% else %}
        <a href="{% url 'app:store_admin' %}">{{a_staff_store_store|upper}}</a>
        {% endif %}
      </span>

      <span>     
          <input type="text" id="side-nav-search-bar" class="side-nav-search-bar active"  onkeyup="myFunction()" onclick="desktopSearchBar()" placeholder="Search for Customers, Products, orders" />
          <ul id="search-display">
            {% for product in store_products %}
            <li><a href="{% url 'app:product_detail' product.slug %}">{{product}}</a></li>
            {% endfor %}
            {% for order in store_orders %}
            <li><a href="{% url 'app:store_order_detail' order.id %}">{{order.id}}</a></li>
            {% endfor %}
            {% for customer in store_customers %}
            <li><a href="{% url 'app:store_customers_details' customer.pk %}">{{customer.full_name}}</a></li>
            {% endfor %}
          </ul>
      </span>
      
      <span>
        <a href="{% url "app:store" a_staff_store_store_slugified %}" class="store-front-btn" target="_blank" rel="noopener noreferrer"><span>StoreFront</span> <i class="fas fa-long-arrow-alt-right"></i></a>
      </span>
   
      <span class="nav-not-acc-sec">
       
      <div id="notification" class="notification"><a href="{% url 'app:notification_page' %}"><span class="notification-count" id="notification-count">{{ user.notifications.unread.count }}</span><i class="fas fa-bell notification-bell"></i></a>
      </div>

        <span class="nav-user-profile" id="nav-user-profile">
          <span id="user-account">
            {% if request.user.avatar %}
            <span class="nav-avatar">
              <img src="{{request.user.avatar.url}}" alt="" />
            </span>
            {% else %}
            <i class="fas fa-user-circle default-avatar"></i>
            {% endif %}
            <span>{{request.user.full_name}}</span> <i id="profile-icon" class="fas fa-caret-down"></i
          ></span>
          <ul id="acc-store-nav-links">
            <li><a href="{% url 'account:user_profile' %}" id="a-nav-link">Profile</a></li>
            <li><a href="{% url 'account:logout' %}" id="a-nav-link">Sign Out</a></li>
          </ul>
        </span>
      </span>

      <div id="toogle"></div>
    </nav>
    <div class="first-instruction-modal" id="first-instruction-modal">
    <div class="above-create-form" id="above-create-form">
      <p>Welcome</p>
    </div>
    <div class="input-container" id="input-container">
      <div id="amount">Before anything, it is highy important you do these
        <ul>
          <li>Set your default currency in settings</li>
          <li>Add you bank account details for payout</li>
          <li>Create a category before adding a product</li>
          <li>Add a valid address for order pickup</li>
          <li>Set a logistics company for deliveries</li>
        </ul>
      </div>
    </div>
  
      <button class="form-btn" id="form-btn">ok</button>

  </div>
    <div class="main-container-large">
      {% block content %} 
      {% endblock %}</div>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  <script>
    var minNotification = document.getElementsByClassName("min-notification");
    for (var i = 0; i < minNotification.length; i++) {
      if (i > 4) {
        minNotification[i].style.display = "none";
      }
    }
  </script>
  </body>
</html>

app/templates/navs/store-side-nav.html

<div class="store-sidenav" id="store-sidenav">
    <span class="store-sidenav-seg">
      <p>{{a_staff_store_store |capfirst }}</p>
      <span>     
          <input type="text" id="side-nav-search-bar-mobile" class="side-nav-search-bar active mobile"  onkeyup="myFunction()" onclick="storeMobileSearchBar()" placeholder="Search for Customers, Products, orders" />
          <ul id="search-display-mobile">
            {% for product in store_products %}
            <li><a href="{% url 'app:product_detail' product.slug %}">{{product}}</a></li>
            {% endfor %}
            {% for order in store_orders %}
            <li><a href="{% url 'app:store_order_detail' order.id %}">{{order.id|truncatechars:20}}</a></li>
            {% endfor %}
            {% for customer in store_customers %}
            <li><a href="{% url 'app:store_customers_details' customer.pk %}">{{customer.full_name}}</a></li>
            {% endfor %}
          </ul>
      </span>
      <ul>
        <li><a href="{% url 'app:store_admin' %}">My Store</a></li>
        <li><a href="{% url 'app:store_wallet' %}">Wallet</a></li>
        <li><a href="{% url 'app:all_customers' %}">Customers</a></li>
        <li><a href="{% url 'app:store_orders' %}">Orders</a></li>
        <li><a href="{% url 'app:wishlist' %}">WishList</a></li>
        <li><a href="{% url 'app:transanction_history' %}">Transanction History</a></li>
      </ul>
    </span>
    <span class="store-sidenav-seg">
      <p>Catalog</p>
      <ul>
        <li><a href="{% url 'app:store_products' %}">All Products</a></li>
        <li><a href="{% url 'app:create_product' %}">Add Product</a></li>
        <li><a href="{% url 'app:all_category' %}">Category</a></li>
        <li><a href="{% url 'app:store_review_list' %}">Reviews</a></li>
      </ul>
    </span>
    <span class="store-sidenav-seg">
      <p>Marketing</p>
      <ul>
        <li><a href="{% url 'app:discount_products' %}">Discount</a></li>
        <li><a href="{% url 'app:all_coupons' %}">Coupon</a></li>
        <li><a href="{% url 'app:newsletter_page' %}">Newsletter</a></li>
      </ul>
    </span>
    <span class="store-sidenav-seg">
      <p>Store Settings</p>
      <ul>
        {% if request.user.store_creator == True %}
        <li><a href="{% url 'account:store_account' %}">Store Settings</a></li>
        <!-- <li><a href="{% url 'app:yearly_subscription_plans' %}">Subscription</a></li> -->
        {% endif %}
        <li><a href="{% url 'account:user_profile' %}">User Account</a></li>
        <li><a href="{% url 'app:store_staff_page' %}">Staff Account</a></li>
        {% if request.user.store_creator == False %}
        {% if multiple_store_staff %}
        <li><a href="{% url 'account:staff_stores' %}">Switch Store</a></li>
        {% endif %}
        {% endif %}
        <li><a href="{% url 'app:shipping_method_list' %}">Logistics Price</a></li>
        {% if request.user.is_superuser %}
        <li><a href="{% url 'app:shipping_company_list' %}">Logistics Company</a></li>
        {% endif %}
      </ul>
    </span>
  </div>