account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PasswordResetConfirmForm, PasswordResetForm

app_name = "account"

urlpatterns = [
    path(
        "activate/<slug:uidb64>/<slug:token>)/",
        views.account_activate,
        name="activate_account",
    ),
    path("register/", views.account_register, name="register"),
    path("login/", views.account_login, name="login"),
    path("logout/", views.account_logout, name="logout"),
    path("settings/profile/", views.user_profile, name="user_profile"),
    path("settings/store-account/", views.store_account, name="store_account"),
    path("delete/", views.account_delete, name="delete_account"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/user/password-reset-form.html",
            success_url="password-reset-email-confirm",
            email_template_name="account/user/password-reset-email.html",
            form_class=PasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/user/password-reset-confirm.html",
            success_url="/account/password-reset-complete/",
            form_class=PasswordResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/password-reset-email-confirm/",
        TemplateView.as_view(template_name="account/user/password-reset-success.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        TemplateView.as_view(template_name="account/user/password-reset-success.html"),
        name="password_reset_complete",
    ),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/user/forgot-password.html", success_url="/"
        ),
        name="change_password",
    ),
    path(
        "store/<slugified_store_name>/add-store-staff/",
        views.store_staff_register,
        name="store_staff_register",
    ),
    path("delete-staff/<str:pk>", views.delete_store_staff, name="delete_store_staff"),
    path("staff-stores/", views.staff_stores, name="staff_stores"),
    path("store/<slugified_store_name>/", views.select_store, name="select_store"),
    path("add-staff/user/", views.add_store_staff, name="add_store_staff"),
    path("create-store/", views.create_store, name="create_store"),
    path("bank-details/", views.bank_details, name="bank_details"),
    path(
        "store/<slug:slugified_store_name>/accept-invitation/<str:email>/<slug:uidb64>/<slug:token>/",
        views.accept_staff_invitation,
        name="accept_staff_invitation",
    ),
    path("bank-auth/<slug:uidb64>/<slug:token>/<account_number>/<account_name>/<bank_name>/<bank_code>/", views.bank_auth, name="bank_auth"),
]

app/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "app"


urlpatterns = [
    path("", views.home_page, name="base"),
    path("create-product/", views.create_product, name="create_product"),
    path("edit/product/<slug>", views.edit_product, name="edit_product"),
    path("delete/product/<slug>", views.delete_product, name="delete_product"),
    path("add-wishlist/<slug>", views.add_wishlist, name="add_wishlist"),
    path("remove-wishlist/<slug>", views.remove_wishlist, name="remove_wishlist"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wallet/", views.store_wallet, name="store_wallet"),
    path(
        "products/",
        views.a_store_all_products,
        name="store_products",
    ),
    path(
        "product/<slug:slug>/",
        views.product_detail,
        name="product_detail",
    ),
    path(
        "store/<slugified_store_name>/category/<slug:slug>/products/",
        views.store_category_products,
        name="store_category_products",
    ),
    path(
        "store/<slugified_store_name>/collections",
        views.all_store_products,
        name="all_store_products",
    ),
    path("store/", views.store_admin, name="store_admin"),
    path("store/<slugified_store_name>/", views.store, name="store"),
    path("categories/", views.all_category, name="all_category"),
    path("create-category/", views.add_category, name="create_category"),
    path("edit-category/<slug:slug>/", views.edit_category, name="edit_category"),
    path("delete-category/<slug:slug>/", views.delete_category, name="delete_category"),
    path("discount-products/", views.discount_products, name="discount_products"),
    path("coupon/", views.all_coupons, name="all_coupons"),
    path("create-coupon/", views.create_coupon, name="create_coupon"),
    path("delete-coupon/<str:pk>/", views.delete_coupon, name="delete_coupon"),
    path("customers/", views.all_customers, name="all_customers"),
    path("orders/", views.store_orders, name="store_orders"),
    path("unpaid-orders/", views.unpaid_store_orders, name="unpaid_store_orders"),
    path("order/<uuid:pk>/", views.store_order_detail, name="store_order_detail"),
    path("<slugified_store_name>/review/", views.store_review, name="store_review"),
    path(
        "<slugified_store_name>/create/review/product/<slug:slug>/",
        views.product_store_review,
        name="product_store_review",
    ),
    path("reviews/", views.store_review_list, name="store_review_list"),
    path("review/<str:pk>/", views.store_review_detail, name="store_review_detail"),
    path(
        "yearly/subscriptions/",
        views.yearly_subscription_plans,
        name="yearly_subscription_plans",
    ),
    path(
        "monthly/subscriptions/",
        views.monthly_subscription_plans,
        name="monthly_subscription_plans",
    ),
    path(
        "transanction-history/", views.transanction_history, name="transanction_history"
    ),
    path("store-staff/", views.store_staff_page, name="store_staff_page"),
    path("shipping/", views.shipping_method_list, name="shipping_method_list"),
    path(
        "notification/mark-as-read/<str:id>/",
        views.mark_notification_read,
        name="mark_notification_read",
    ),
    path(
        "customer/detail/<str:pk>/",
        views.store_customers_details,
        name="store_customers_details",
    ),
    path(
        "store/<slugified_store_name>/product/<slug:slug>/reviews/",
        views.product_review_list,
        name="product_review_list",
    ),
    path("company/reviews/", views.company_review, name="company_review"),
    path("company/team/", views.company_team, name="company_team"),
    path("get-state/<iso2>/", views.get_state, name="get_state"),
    path("get-city/<iso2>/", views.get_state, name="get_city"),
    path("notifications/", views.notification_page, name="notification_page"),
    path("newsletter/", views.newsletter_page, name="newsletter_page"),
    path("generate/newsletter/", views.generate_store_newsletter, name="generate_store_newsletter"),
    path("draft/newsletter/", views.draft_newsletter, name="draft_newsletter"),
    path("publish/newsletter/", views.publish_newsletter, name="publish_newsletter"),
    path("publish/draft/newsletter/<str:pk>", views.publish_draft_newsletter, name="publish_draft_newsletter"),
    path("delete/newsletter/<str:pk>/", views.delete_draft_newsletter, name="delete_draft_newsletter"),
    path("edit/draft/newsletter/<str:pk>/", views.edit_draft_newsletter, name="edit_draft_newsletter"),
    path("unsubscribe-newsletter/<slugified_store_name>/", views.unsubscribe_newsletter, name="unsubscribe_newsletter"),
    path("resubscribe-newsletter/<slugified_store_name>/", views.resubscribe_newsletter, name="resubscribe_newsletter"),
    path(
        "create/shipping-method/", views.add_shipping_method, name="add_shipping_method"
    ),
    path(
        "edit/shipping-method/<str:pk>",
        views.edit_shipping_method,
        name="edit_shipping_method",
    ),
    path(
        "delete/shipping-method/<str:pk>",
        views.delete_shipping_method,
        name="delete_shipping_method",
    ),
    path("shipping-company/", views.shipping_company_list, name="shipping_company_list"),
    path("add/shipping-company/", views.add_shipping_company, name="add_shipping_company"),
    path("edit/shipping-company/<str:pk>", views.edit_shipping_company, name="edit_shipping_company"),
    path("delete/shipping-company/<str:pk>", views.delete_shipping_company, name="delete_shipping_company"),
    path("faqs/", TemplateView.as_view(template_name='faqs.html'), name="faqs" ),
    path("terms/", TemplateView.as_view(template_name='terms.html'), name="terms" ),
    path("privacy-policy/", TemplateView.as_view(template_name='privacy-policy.html'), name="privacy_policy" ),
    
]

core/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls", namespace="app")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("account/", include("account.urls")),
    path("customer/", include("customer.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    re_path(
        "^inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "app.views.custom_error_404"
handler500 = "app.views.custom_error_500"

customer/urls.py
from django.urls import path

from . import views

app_name = "customer"

urlpatterns = [
    path(
        "register/<slugified_store_name>/",
        views.customer_register,
        name="customer_register",
    ),
    path(
        "login/<slug:slugified_store_name>/",
        views.customer_login,
        name="customer_login",
    ),
    path(
        "logout/<slugified_store_name>/", views.customer_logout, name="customer_logout"
    ),
    path(
        "register/existing-user/<slugified_store_name>/",
        views.existing_user_customer_register,
        name="existing_user_customer_register",
    ),
    path(
        "<slugified_store_name>/logout", views.customer_logout, name="customer_logout"
    ),
    path(
        "<slugified_store_name>/product/<slug:slug>/",
        views.customer_product_detail,
        name="customer_product_detail",
    ),
    path(
        "<slugified_store_name>/profile/",
        views.customer_profile,
        name="customer_profile",
    ),
    path(
        "<slugified_store_name>/wishlist/",
        views.customer_wishlist,
        name="customer_wishlist",
    ),
    path(
        "add-wishlist/<slug>", views.customer_add_wishlist, name="customer_add_wishlist"
    ),
    path(
        "remove-wishlist/<slug>",
        views.customer_remove_wishlist,
        name="customer_remove_wishlist",
    ),
    path("<slugified_store_name>/address/", views.address_list, name="address_list"),
    path(
        "<slugified_store_name>/address/create/",
        views.create_address,
        name="create_address",
    ),
    path(
        "<slugified_store_name>/set-default/address/<str:id>/",
        views.set_default_address,
        name="set_default_address",
    ),
    path(
        "<slugified_store_name>/edit/address/<str:id>/",
        views.edit_address,
        name="edit_address",
    ),
    path(
        "<slugified_store_name>/delete/address/<str:id>/",
        views.delete_address,
        name="delete_address",
    ),
    path("my-stores/", views.customer_stores, name="customer_stores"),
    path("<slugified_store_name>/delete", views.delete_account, name="delete_account"),
    path(
        "<slugified_store_name>/orders/", views.customer_orders, name="customer_orders"
    ),
    path(
        "<slugified_store_name>/unpaid-orders/",
        views.unpaid_customer_orders,
        name="unpaid_customer_orders",
    ),
    path(
        "<slugified_store_name>/order/<uuid:pk>/",
        views.customer_order_detail,
        name="customer_order_detail",
    ),
    path(
        "<slugified_store_name>/reviews/",
        views.customer_reviews,
        name="customer_reviews",
    ),
    path(
        "<slugified_store_name>/review/<str:pk>/",
        views.customer_review_detail,
        name="customer_review_detail",
    ),
    path(
        "<slugified_store_name>/review/edit/<str:pk>",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "<slugified_store_name>/review/delete/<str:pk>",
        views.delete_review,
        name="delete_review",
    ),
    path(
        "<slugified_store_name>/delete/unpaid-order/<str:pk>/",
        views.delete_unpaid_order,
        name="delete_unpaid_order",
    ),
]

customer/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from account.models import *

# Create your models here.


class Customer(models.Model):
    full_name = models.CharField(max_length=300)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=300)
    password2 = models.CharField(max_length=300)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name="customer")
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Address(models.Model):
    id = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, unique=True
    )
    customer = models.ForeignKey(
        Customer, verbose_name=_("Customer"), on_delete=models.CASCADE
    )
    postcode = models.CharField(_("Postcode"), max_length=50, blank=True, null=True)
    address_line = models.CharField(_("Address Line 1"), max_length=255)
    address_line2 = models.CharField(
        _("Address Line 2"), max_length=255, blank=True, null=True
    )
    delivery_instructions = models.CharField(
        _("Delivery Instructions"), max_length=255, blank=True, null=True
    )
    country = models.CharField(_("Country"), max_length=200)
    state = models.CharField(_("State"), max_length=200)
    default = models.BooleanField(_("Default"), default=False)
    country_code = models.CharField(max_length=10, blank=True, null=True)  
    state_code = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.address_line

customer/forms.py
from django import forms
from django.forms import ModelForm
from django.shortcuts import get_object_or_404, redirect, render

from account.models import User

from .models import *


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ["full_name", "email", "password", "password2"]

        widgets = {
            "full_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Full Name"}
            ),
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Email"}
            ),
            "password": forms.PasswordInput(
                attrs={"class": "form-control", "placeholder": "Password"}
            ),
            "password2": forms.PasswordInput(
                attrs={"class": "form-control", "placeholder": "Confirm Password"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)


class ExistingUserCustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ["email"]

        widgets = {
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Email"}
            ),
        }

        def __init__(self, *args, **kwargs):
            super(ExistingUserCustomerForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data["email"]
        user = User.objects.filter(email=email)
        if not user:
            raise forms.ValidationError("User does not exist")
        return email


class AddressForm(ModelForm):
    class Meta:
        model = Address
        exclude = ["customer"]

        widgets = {
            "full_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Full Name"}
            ),
            "phone": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "+349 0854 9885"}
            ),
            "postcode": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Post Code"}
            ),
            "address_line": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Address Line"}
            ),
            "address_line2": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Additional address(Not Compulsory)",
                }
            ),
            "delivery_instructions": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Delivery Instructions"}
            ),
            "country": forms.Select(attrs={"class": "form-control"}),
            "state": forms.Select(attrs={"class": "form-control"}),
        }

app/templates/customer/address-create.html
{% extends 'navs/customer-nav.html' %} {% load static %} 
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
  <title>{{store.store_name }} - {{request.user.full_name}}</title>
  {% endblock %}
</head>
<body>
{% block content %}
<div class="store-page-container">
  <span class="customer-profile-container">
    {% include 'navs/customer-side-nav.html' %}
    <div class="account-form-container">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="above-create-form">
          <p>My Address</p>
        </div>

        <div class="acc-form-seg">
            <p>Location Info</p>
          <div class="input-container">
            <label for="postcode">Post Code</label>
            <p>{{ address_form.postcode.errors }}</p>
            {{address_form.postcode}}
          </div>

          <div class="input-container">
            <label for="address_line">Address<span class="form-required">*</span></label>
            <p>{{ address_form.address_line.errors }}</p>
            {{address_form.address_line}}
          </div>

          <div class="input-container">
            <label for="address_line2">Address 2</label>
            <p>{{ address_form.address_line2.errors }}</p>
            {{address_form.address_line2}}
          </div>

          <div class="input-container">
            <label for="delivery_instructions">Delivery Instructions</label>
            <p>{{ address_form.delivery_instructions.errors }}</p>
            {{address_form.delivery_instructions}}
          </div>
          
          <div class="input-container">
            <label for="country">Country<span class="form-required">*</span></label>
            <p>{{ address_form.country.errors }}</p>
            <select name="country" class="countries form-control" id="country">
              {% if store.country %}
              <option value="{{store.country_code}}">{{store.country}}</option>
              {% else %}
              <option value="">Select Country</option>
              {% endif %}
               {% for key, value in country_names %}
              <option value="{{ value }}">{{ key }}</option>
              {% endfor %}
            </select>
          </div>
       

          <div class="input-container">
            <label for="state">State<span class="form-required">*</span></label>
            <p>{{ address_form.state.errors }}</p>
            <select name="state" class="states form-control" id="state">
              {% if store.state %}
              <option value="{{store.state_code}}">{{store.state}}</option>
              {% else %}
              <option value="">Select State</option>
              {% endif %}
            </select>
          </div>
      

        <div class="form-btn-container">
          <button class="form-btn" type="submit">
            {% if 'create' in request.get_full_path %}
            Create
            {% else %}
            Update
            {% endif %}
          </button>
        </div>
        </div>
      </form>
    </div>
  </span>
</div>
</body>
</html>
<script>
$(document).ready(function(){
    $("#country").change(function(){
        var country = $(this).val();
        console.log(country);
        $.ajax({
          type: "POST",
          url : "{% url 'app:get_state' 'country' %}".replace('country', country),
          
          data: 
          {
            country: country,
            csrfmiddlewaretoken: '{{ csrf_token }}'
          },
          success: function(data){
            console.log(data);        
            $('#state').empty();
            $.each(data.states, function(key, value) {
              $('#state').append($('<option>', {value: value[1], text: value[0] }));
            });
            
          }
      });
     
    });
});
</script>
{% endblock %}







app/templates/customer/address-list.html
{% extends 'navs/customer-nav.html' %} {% load static %}{% block title %}<title>
  Shopit - {{request.user.full_name }} Shipping Address
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  <span class="customer-profile-container">
    {% include 'navs/customer-side-nav.html' %}
    <div class="store-content-container">
      <span class="store-products-container">
        <p>My Shipping Address</p>
        <span>
          <a href="{% url 'customer:create_address' store.slugified_store_name %}">Add Address</a>
        </span>
        {% if address_list %}
        <span class="customer-address-container">
          {% for address in address_list %}
          <span>
            <p>{{ address.address_line }}</p>
            <div>
              <span>{{ address.city }},</span>
              <span>{{ address.state }},</span>
              <span>{{ address.country }}</span>
            </div>
            <span>
              <a href="{% url 'customer:edit_address' store.slugified_store_name address.id %}">Edit</a>
              <span>
                {% if address.default == True %}
                <span>Default</span>
                {% else %}
                <a href="{% url 'customer:set_default_address' store.slugified_store_name address.id %}">Set as Default</a>
                {% endif %}
              </span>
              <a href="{% url 'customer:delete_address' store.slugified_store_name address.id %}">Delete</a>
            </span>
          </span>
          {% endfor %}
        </span>
        {% else %}
        <p>You have no shipping address</p>
        {% endif %}
      </span>
    </div>
  </span>
  {% endblock %}
</div>

app/templates/customer/customer-order.html
{% extends 'navs/customer-nav.html' %} {% load static %}{% load humanize %}{% block title %}<title>
 Shopit - {{request.user.full_name }} - {% if 'unpaid' in request.get_full_path %}Unpaid{% endif %} Order
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  <span class="customer-profile-container">
    {% include 'navs/customer-side-nav.html' %}
    <div class="store-content-container">
      <span class="store-products-container">
        <p>My {% if 'unpaid' in request.get_full_path %}Unpaid{% endif %} Orders</p>
          <p>
            {% if 'unpaid' in request.get_full_path %}
            <a href="{% url 'customer:customer_orders' store.slugified_store_name %}">Paid Orders</a>           
              <small>Unpaid orders will be deleted after 30 days</small>
            {% else %}
            <a href="{% url 'customer:unpaid_customer_orders' store.slugified_store_name %}">Unpaid Orders</a>
            {% endif %}
          </p>
        <div class="table-container">
          <table class="store-products-table">
          <tr class="table-rows">
            <th>Order Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Amount</th>
            <th>Billing Status</th>
            {% if 'unpaid' in request.get_full_path %}
            <th>Delete</th>
            {% endif %}
          </tr>
          {% for order in orders %}
         
          <tr class="table-rows">
            <td><a href="{% url 'customer:customer_order_detail' store.slugified_store_name order.pk %}">{{order.id|truncatechars:12}}</a></td>
          <td> {% if payment.full_name %}
            {{ payment.full_name }}
            {% elif payment.order.user %}
            {{payment.order.user.full_name}}
            {% else %}
           {{customer.full_name}}
            {% endif %}
          </td>
          <td>
            {% if payment.order.user %}
            {{ order.user.email }}
            {% elif payment.email %}
            {{ payment.email}}
            {% else %}
            {{customer.email}}
            {% endif %}
          </td>
          <td> 
            {{order.currency_symbol}}
            {% if payment.currency %}
              {{ payment.amount|intcomma}}
            {% else %}
            {{ order.amount|intcomma }}
            {% endif %}         
          </td>
          <td>{% if order.billing_status == True %}
            Paid
            {% else %}
            Unpaid
            {% endif %}
          </td>
           {% if 'unpaid' in request.get_full_path %}
          <td>
            <a href="{% url 'customer:delete_unpaid_order' slugified_store_name=store.slugified_store_name pk=order.pk %}">Delete</a>
          </td>
           {% endif %}
          </tr>
          {% endfor %}
        </table>
        </div>
        
        {% if orders.has_other_pages %}
      <span class="pagination">
        <span>
          {% for i in orders.paginator.page_range %} {% if orders.number == i %} Showing
          {{orders.start_index }} of {{ orders.end_index }} of {{ orders.paginator.count }} 
          entries {% endif %} {% endfor %}
        </span>

        <span>
          {% if orders.has_previous %}
          <a href="?page={{ orders.previous_page_number }}"><i class="fas fa-arrow-left"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-left disable"></i></span>
          {% endif %} {% if orders.has_next %}
          <a href="?page={{ orders.next_page_number }}"><i class="fas fa-arrow-right"></i></a>
          {% else %}
          <span><i class="fas fa-arrow-right disable"></i></span>
          {% endif %}
      </span>
      </span>
      {% endif %}
    </div>
  </span>
  {% endblock %}
</div>

app/templates/customer/customer-profile.html
{% extends 'navs/customer-nav.html' %} {% load static %} {% block title %}
<title>{{store.store_name }} - {{request.user.full_name}}</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  <span class="customer-profile-container">
    {% include 'navs/customer-side-nav.html' %}
    <div class="account-form-container">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="above-create-form">
          <p>My Profile</p>
        </div>

        <div class="acc-form-seg">
          <p>Basic Info</p>
          <div class="input-container">
            <label for="avatar">Avatar<span class="form-required">*</span></label>
            <p>{{ userprofileform.avatar.errors }}</p>
            <div>{{ userprofileform.avatar }}</div>
          </div>

          <div class="input-container">
            <label for="name">Full Name<span class="form-required">*</span></label>
            <p>{{ userprofileform.full_name.errors }}</p>
            <div>{{ userprofileform.full_name }}</div>
          </div>

          <div class="input-container">
            <label for="phone_number">Phone Number</label>
            <p>{{ userprofileform.phone_number.errors }}</p>
            {{userprofileform.phone_number}}
          </div>
        </div>

        <div class="form-btn-container">
          <button class="form-btn" type="submit">Update</button>
        </div>
      </form>


      <div class="profile-btm-container">
      <a class="update-btn" href="{% url 'account:change_password' %}">Forgot Password</a>
      <a class="delete-btn" href="{% url 'customer:delete_account' store.slugified_store_name %}">Delete Account</a>
    </div>
    </div>
  </span>
</div>

{% endblock %}

app/templates/customer/customer-review-detail.html
{% extends 'navs/customer-nav.html' %} {% load static %} {% block title %}<title>
 Shopit - {{request.user.full_name }} Review
</title>
{% endblock %} {% block content %}
<div class="store-page-container">
  <span class="customer-profile-container">
    {% if request.user.is_authenticated %}
    {% include 'navs/customer-side-nav.html' %}
    {% endif %}
    {% if request.user.is_authenticated %}
    <div class="store-content-container">
      {% else %}
    <div class="review-content-container">
      {% endif %}
      <span class="review-container">
        
        <p>{{review.title}}</p>
        <div>
          {% if review.product %}
          <div class="review-realated-product">
            <p>Related Product</p>
            <div>
              
              <a
                href="{% url 'customer:customer_product_detail' slugified_store_name=store.slugified_store_name slug=review.product.slug %}"
                >{{review.product}}</a
              >
            </div>
          </div>
          {% endif %}

          <div>
            
            </span>
            <p>Comment</p>
            <div>
              {{review.comment}}
            </div>
          </div>
          <small>By {{review.full_name}} - {{review.created|timesince}}</small>
          {% if request.user.is_authenticated %}
            {% if request.user.email == review.email %}
            <span>
              <button type="button" class="update-btn">
                <a href="{% url 'customer:edit_review' slugified_store_name=store.slugified_store_name pk=review.id %}"><i class="far fa-edit"></i>Update</a>
              </button>
              <button type="button" class="delete-btn">
                <a href="{% url 'customer:delete_review' slugified_store_name=store.slugified_store_name pk=review.id %}"><i class="fas fa-trash-alt"></i>Delete</a>
              </button>
              {% endif %}
              {% endif %}
        </div>
      </span>
    </div>
  </span>
  {% endblock %}
</div>